import { SignIn } from "@clerk/nextjs";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const PostFeed = () => {
  const { data: posts } = api.example.posts.useQuery();
};

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex border-b border-slate-400 p-4">
        <div className="flex">
          {!isSignedIn && (
            <div className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">
              <SignInButton />
            </div>
          )}
        </div>
        {isSignedIn && (
          <div>
            <p>You are signed in!</p>
            <div className="rounded bg-red-500 px-4 py-2 font-bold text-white hover:bg-red-700">
              <SignOutButton />
            </div>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
